postlight/lux

- bin/lux
- examples/social-network/package.json
- examples/todo/package.json
- package.json
- src/packages/cli/index.js
- src/packages/cli/templates/package-json.js
This PR resolves an error where the `--use_strict` flag in the shebang line of `bin/lux` does not find `node` on linux.
> fix: shebang line not finding node on linux

- examples/social-network/package.json
- examples/todo/package.json
- package.json
- src/packages/application/index.js
- src/packages/cli/commands/serve.js
- src/packages/cli/index.js
- src/packages/cli/templates/package-json.js
This PR fixes an issue where the `Lux Server listening on {port}` message is written to stdout before all worker processes are ready.
**Before:**
**After:**
> fix: listening message dispatched before workers are ready

- src/packages/logger/index.js
The logger is producing an incorrect date.
```
[4/1/16 2:55:25 PM] Starting Lux Server with 8 worker processes
```
Should be
```
[4/18/16 2:55:25 PM] Starting Lux Server with 8 worker processes
```
> fix: logger date incorrect

- src/packages/cli/templates/database-json.js
This adds the default port configuration to the database.json configuration when generating the app.
> fix: missing port in database config generation

- package.json
I missed this in #38. [Ora](https://github.com/sindresorhus/ora) should be a runtime dependency.
> fix: make ora a runtime dependency

- README.md
Adds a [Shields.io](http://shields.io/) compliant NPM package badge to `README.md` through [Version Badge](https://badge.fury.io/).
> docs: add npm package badge to README

- .travis.yml
Now that [Node 6 is out](https://nodejs.org/en/blog/announcements/v6-release/), we should run tests against it on Travis.
> chore: test on node 6

- src/packages/controller/index.js
- test/integration/controller.js
Currently the action decorator is [expecting an object](https://github.com/postlight/lux/blob/master/src/packages/controller/decorators/action.js#L16) with a data property as a response. In a future release we will refactor the decorator to evaluate the type of a resolved value of a route action before returning the value back to the Router.
For now, this enables `HEAD` and `OPTIONS` requests.
--
cc @jhliberty
> fix: HEAD and OPTIONS request result in a 404

- bin/lux
This PR allows for the `lux` command to use the locally installed version of Lux if one exists, otherwise the globally installed version of Lux will be used.
**Benefits:**
- Users can work on multiple Lux projects that all use different versions seamlessly
- Upgrading Lux can be done without having to `npm uninstall -g lux-framework; npm install -g lux-framework`
> feat: use local lux install if one exists

- .travis.yml
Gets rid of the following [warning](https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Node.js-v4-(or-io.js-v3)-compiler-requirements) on Travis-CI:
> Starting with io.js 3 and Node.js 4, building native extensions requires C++11-compatible compiler, which seems unavailable on this VM. Please read https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Node.js-v4-(or-io.js-v3)-compiler-requirements.
> test: add correct g++ version for node 4+ in .travis.yml

- package.json
- src/errors/module-missing.js
- src/packages/cli/commands/create.js
- src/packages/cli/commands/destroy.js
- src/packages/cli/commands/generate.js
- src/packages/cli/commands/serve.js
- src/packages/database/errors/invalid-driver.js
- src/packages/database/errors/migrations-pending.js
- src/packages/logger/index.js
- src/packages/server/index.js
- test/test-app/config/environments/development.js
This PR refactors Lux to use [chalk](https://www.npmjs.com/package/chalk) instead of [colors](https://www.npmjs.com/package/colors). Since chalk seems to be the better package and [ora](https://www.npmjs.com/package/ora) has a peer dependency of [chalk](https://www.npmjs.com/package/chalk), it makes sense to use it in place of [colors](https://www.npmjs.com/package/colors).
> refactor: use chalk instead of colors

- src/packages/cli/index.js
Using `-db` doesn't work with commander. This PR removes that option from the `--help` prompt in favor of the longer `--database` flag.
--
Closes #85
> fix: remove short -db flag from lux new cmd

- src/packages/application/index.js
- src/packages/controller/index.js
- test/integration/controller.js
- test/test-app/app/controllers/application.js
- test/test-app/app/controllers/authors.js
- test/test-app/app/controllers/posts.js
This PR fixes the issue of middleware not being executed when added to the `beforeAction` array on a `Controller`.
The reason this bug exists is because #65 introduced many improvements where previously computed properties were moved to it's classes constructor in attempt to prevent multiple executions of a `getter`. The downside of doing this is that class properties will not be installed on the `prototype` until after the constructor is called. This simply moves the `middleware` property back to a computed `getter` function which is later memoized in the `Route` class upon the application's boot so there is no perf regression.
This PR also removes the parent class `Base` from `Controller` which is part of an ongoing refactor to no longer be using `Base` as a parent for packages within …
> fix: middleware functions added in 'beforeAction' not executing

- src/packages/database/model/utils/initialize.js
Tests for this particular issue will be added in a separate PR addressing #77.
--
Closes #106
> fix: column data not consistent across all dbms

- src/packages/database/model/utils/initialize.js
#108 didn't account for the fact that `defaultValue` still needs a type conversion.
> fix: defaultValue is not accounted for in #108

- src/packages/controller/middleware/sanitize-params.js
Fixes a bug  where `/users?include=posts` works as expected but `/users?include=posts,comments` ignores the `include` array.
> fix: using ?include is not working with multiple resources

- src/packages/application/index.js
- src/packages/controller/utils/format-include.js
- src/packages/serializer/index.js
Fixes a bug where `?include=comments&fields[comment]=message` would not optimize the `SELECT ... FROM comments` statement. Also refactors serializer to be more functional and not extend `Base`.
> fix: select statement not being optimized by fields param

- src/packages/database/collection/index.js
- src/packages/database/model/index.js
- src/packages/database/model/utils/fetch-has-many.js
Before:
```sql
SELECT posts.id AS post.id, comments.id AS comments.id
FROM posts
INNER JOIN comments ON comments.post_id = posts.id
```
After:
```sql
SELECT comments.id AS comments.id, comments.post_id AS posts.id
FROM comments
WHERE comments.post_id
IN (1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25)
```
> fix: hasMany relationships are not eager loading properly

- src/packages/application/errors/controller-missing.js
- src/packages/application/errors/index.js
- src/packages/application/errors/serializer-missing.js
- src/packages/application/index.js
We now have the following messages when a file is missing
```
Error: Could not resolve model by name 'user'
Error: Could not resolve controller by name 'users'
Error: Could not resolve serializer by name 'users'
```
Fixes #104
> feat: improve error handling on missing controller & serializer files

- ROADMAP.md
[node-orm2](https://github.com/dresende/node-orm2) references are no longer valid since #65.
> docs: remove node-orm2 references from ROADMAP.md

- src/packages/controller/index.js
- src/packages/route/utils/create-action.js
- src/packages/serializer/index.js
- src/packages/server/index.js
- src/packages/server/responder/index.js
- src/packages/server/responder/response/index.js
- src/packages/server/responder/utils/data-for.js
- src/packages/server/responder/utils/normalize.js
This PR refactors `Serializer` to return objects rather than streams as data will be transformed to a stream before the req/res is completed anyways. Also, Serializer methods now have more appropriate names such as `Serializer#format` vs `Serializer#serializer`.
> refactor: rename serializer methods and return objects

- bin/lux
- src/constants.js
- src/packages/cli/commands/create.js
- src/packages/cli/commands/db-create.js
- src/packages/cli/commands/db-drop.js
- src/packages/cli/commands/db-migrate.js
- src/packages/cli/commands/db-rollback.js
- src/packages/cli/commands/db-seed.js
- src/packages/cli/commands/destroy.js
- src/packages/cli/commands/generate.js
- src/packages/cli/commands/serve.js
- src/packages/cli/index.js
- src/packages/compiler/utils/create-boot-script.js
- src/packages/database/initialize.js
- src/packages/database/utils/connect.js
- src/packages/logger/index.js
- src/packages/logger/initialize.js
- src/packages/pm/cluster/index.js
In order to ensure cross platform compatibility we should use `process.cwd()` instead of `process.env.PWD`.
This PR also moves `ENV` vars to a central `constants.js` file at the root of the `./src` dir where values are normalized and exported for use throughout the project.
> refactor: use process.cwd() instead of process.env.PWD

- bin/lux
- src/packages/cli/commands/serve.js
- src/packages/pm/cluster/index.js
- src/packages/pm/index.js
Some users may want to manage concurrency on their own through docker containers or something similar. This PR disables default clustering and moves it to a `-c (--cluster)` flag for `lux serve`.
> feat: do not cluster by default use -c || --cluster

- src/packages/cli/templates/application.js
Fixes an issue where generating a new app with multiple dashes in the app name will cause the output of the classname to have a dash in it.  Previously only the first dash was removed, the rest were kept.  This results in a syntax error and fails to start the app up.
> fix: fixes #187 issue with class name generation with multiple dashes

- src/packages/database/model/index.js
- src/packages/database/model/initialize-class.js
- src/packages/database/relationship/index.js
- src/packages/database/relationship/interfaces.js
- src/packages/database/relationship/utils/related-for.js
- src/packages/serializer/index.js
- src/utils/uniq.js
Models now return a `Promise` when accessing a relationship. If the related record have been eager loaded with includes it will immediately resolve to the eager loaded value. Otherwise, it will load the related records from the database and resolve with the result.
*Async/Await*
```javascript
const post = await Post.find(1);
console.log(await post.author);
// => Author {}
```
*Promises*
```javascript
Post.find(1)
.then(post => post.author)
.then(author => console.log(author));
// => Author {}
```
--
Closes #181
> feat: return a promise from relationships

- scripts/flow.js
This PR ensures you will get the output from a failed `npm run flow` cmd.
> fix: display correct error messages from flow script

- src/packages/server/responder/utils/data-for.js
According to the JSON API spec, `errors` should be a top level document (http://jsonapi.org/format/#document-top-level).
Currently when an error is returned, it is included in the `data` top level member. This patch fixes this behaviour.
> Errors should be a top level member

- src/packages/serializer/index.js
- src/packages/server/responder/utils/data-for.js
- test/integration/serializer.js
According to the spec (http://jsonapi.org/format/#document-resource-object-identification), the value of the resource object identifiers `id` field should be a string.
> Resource IDs must be strings

- package.json
- src/packages/route/utils/create-action.js
Currently, the domain protocol is hardcoded to http. The `encrypted` attribute is set in the request's `connection` when the request is made via HTTPS.
We should use this information to correctly deduce the used protocol.
> Deduce domain protocol from connection

- src/packages/cli/commands/create.js
- src/packages/cli/commands/destroy.js
- src/packages/cli/commands/generate.js
- src/packages/cli/templates/middleware.js
> Feat: Added generator for middleware

- src/packages/database/model/index.js
> fix: empty 'fields' params cause all keys of a resource to be exposed

- decl/bluebird.js
- package.json
- scripts/build/cli.js
- src/packages/cli/commands/create.js
- src/packages/cli/commands/dbcreate.js
- src/packages/cli/commands/dbrollback.js
- src/packages/cli/commands/destroy.js
- src/packages/cli/commands/generate.js
- src/packages/compiler/index.js
- src/packages/compiler/utils/create-boot-script.js
- src/packages/compiler/utils/create-manifest.js
- src/packages/database/utils/pending-migrations.js
- src/packages/fs/index.js
- src/packages/fs/interfaces.js
- src/packages/fs/utils/create-resolver.js
- src/packages/fs/utils/exists.js
- src/packages/fs/utils/rmrf.js
- src/packages/watcher/index.js
- src/packages/watcher/initialize.js
- src/packages/watcher/interfaces.js
- src/utils/exec.js
Removes `bluebird` in favor of native APIs.
This refactor was implemented because of the following:
- One less dependency is always nice
- Flow plays much nicer w/ native `Promise`s
- We didn't use `bluebird` for anything other than `promisifyAll` for `fs` methods which have since been converted manually which gives us significantly improved type safety
> refactor: remove bluebird in favor of native apis

- bin/lux
Addresses https://github.com/postlight/lux/issues/263
I considered automatically printing the help after the error message, but I decided it would get annoying to see the whole error message if you just entered a typo. It also made it more difficult to focus in on the fact that there _was_ and error in the first place. So I went with this.
I pulled in chalk, since you're using it elsewhere, but if you don't like it, I can remove it!
Last: In an ideal world, we'd look at the text of the command and see if it's close to an existing lux command and present that to the user, like a "did you mean..." — but I'm trying to avoid letting this creep too far for a simple feature addition. 😄
> Feat: Added default fallback for CLI

- src/packages/compiler/index.js
Addresses https://github.com/postlight/lux/issues/272
The documentation for rollup-plugin-alias isn't great, but this appears to be the correct usage. I tested it in the social-network example app and the test-app and it's working as expected.
> Feat: aliased app dir for easier imports

- src/packages/logger/request-logger/templates.js
Addresses #259. I'm very open to criticism here. This works, and should work even when the number of digits varies significantly. E.g., 
```
Stats
4 ms TagsController#show
24 ms Total
378 ms Actual
```
It operates on the assumption that the actual time will always be the longest (which... should be the case, correct?). I don't love that the pad function has to calculate the maxLength multiple times, but it seemed necessary given the current state of the template function, and I didn't want to change that too much. 
But yeah, open to suggestions.
> Fix: Lining up stats in debug logger when ms length differs

- src/packages/logger/request-logger/templates.js
Closes #294 
--
Turns out, the number `Infinity` was causing this bug.
> fix: pad function is failing due to negative values

- examples/social-network/config/environments/development.js
- src/packages/application/initialize.js
- src/packages/config/index.js
- src/packages/config/interfaces.js
- src/packages/server/index.js
- src/packages/server/interfaces.js
- src/packages/server/utils/set-cors-headers.js
This pull request adds the ability to configure CORS headers via the config. There's a lot of new-to-me work on this one in terms of Flow, so I'm including some notes.
--
Closes #282
> Feat: Added CORS to config

- examples/social-network/app/models/user.js
I looked into the reason this `beforeSave` hook was failing on postgres, per #306, and here's what I found:
The original code in the hook is doing a check to see if `id` is `null`, which fits with the sqlite3 driver, but when using postgres id isn't null—it's a string that looks like `nextval('users_id_seq'::regclass)`. 
For the purpose of checking/fixing in the social-network example, I'm doing a typeof check on id since the id of a saved model should be a number, which works, but it seems like maybe there's an underlying issue here: 
It seems like the id check you're doing here is intended to determine whether or not a model has been persisted to the database, and I'm wondering if this a feature you might want to add—sort of like …
> Fix: id null check fails if using postgres

- src/packages/cli/templates/package-json.js
I added the minimum node version to the package.json template. This is a good practice, and also necessary for various deployment environments. Added in pursuit of #320.
> Feat: Added minimum node version to package.json template

- bin/lux
In pursuit of #320, I discovered that NODE_ENV and PORT environment variables were being overwritten by the lux CLI. This pull request only writes to process.env if a value is given to the CLI; if not, it writes defaults to process.env only if the value has not already been set.
> Fix: Environment variables overwritten by lux CLI

- README.md
Some of these are pure opinion, so let me know what you do and don't want merged!
> docs: small readme typos/rephrasings

- src/packages/database/model/index.js
- src/packages/database/query/index.js
- src/packages/serializer/index.js
This PR adds a chainable `#distinct()` method to the query interface.
```javascript
import Post from 'app/models/post';
Post.distinct('title' /*, 'body', ...etc */).where({
isPublic: true
});
// SELECT DISTINCT "posts"."title" AS "title" FROM "posts" WHERE "posts"."is_public" = TRUE
```
--
Closes #332
> feat: add #distinct() query method

- src/packages/cli/templates/model-migration.js
Fixes a bug where newly generated migrations contain the full filename rather than just the table name.
> fix: model migration table name includes filename

- src/packages/database/relationship/index.js
- src/packages/database/relationship/utils/getters.js
- src/packages/database/test/relationship.test.js
- test/test-app/app/controllers/admin/images.js
- test/test-app/app/controllers/images.js
- test/test-app/app/controllers/posts.js
- test/test-app/app/models/action.js
- test/test-app/app/models/image.js
- test/test-app/app/models/post.js
- test/test-app/app/models/reaction.js
- test/test-app/app/routes.js
- test/test-app/app/serializers/admin/images.js
- test/test-app/app/serializers/images.js
- test/test-app/app/serializers/posts.js
- test/test-app/db/migrate/2016051621421145-create-reactions.js
- test/test-app/db/migrate/2016092015442134-create-images.js
- test/test-app/db/seed.js
> test: add unit tests for relationships module in database package

- src/packages/fs/test/fs.test.js
- src/packages/fs/test/watcher.test.js
This PR prevents relative `tmp` dirs from being used in `fs` tests.
> fix: use path.sep to resolve root tmp dirs in fs tests

- src/packages/application/utils/create-controller.js
- src/packages/controller/index.js
- src/packages/controller/interfaces.js
- src/packages/router/route/action/enhancers/resource.js
- src/packages/router/route/action/enhancers/track-perf.js
- src/packages/router/route/action/index.js
- src/packages/router/route/action/test/track-perf.test.js
- src/packages/router/route/index.js
- src/packages/router/route/test/route.test.js
- src/utils/sleep.js
- src/utils/test/sleep.test.js
- test/utils/mocks.js
Adds `afterAction` middleware hook to the public `Controller` API.
--
After action provides a way to easily alter the response data for a particular request.
In the example below we will add copyright info to a meta object of the response data.
```javascript
import { Controller } from 'lux-framework';
async function authenticate(req, res) {
if (!req.currentUser) {
return false;
}
}
async function addCopyright(req, res, data) {
if (data && typeof data === 'object' && !Array.isArray(data)) {
return {
...data,
meta: {
...(data.meta || {}),
copyright: 'Copyright (c) 2016 Postlight'
}
};  
}
return data;
}
class ApplicationController extends Controller {
beforeAction = [
authenticate
];
afterAction = [
addCopyright
];
}
export default ApplicationController;
```
Like the `beforeAction` hook …
> feat: add after-action middleware hook to controller

- src/packages/server/request/index.js
- src/packages/server/request/interfaces.js
Adds the ability to access `req.action` (e.g `'index', `'show'`, etc.`) and `req.controller` (e.g `PostsController`).
> feat: expose controller and action in public request api

- src/packages/database/model/index.js
- src/packages/database/test/model.test.js
Seeing a pretty significant perf increase from this change!
*Before:*
```bash
$ wrk -c 64 -d 30 http://localhost:4000/posts/1
Running 30s test @ http://localhost:4000/posts/1
2 threads and 64 connections
Thread Stats   Avg      Stdev     Max   +/- Stdev
Latency    50.53ms   23.54ms 234.52ms   72.10%
Req/Sec   646.46     82.86   808.00     78.83%
38676 requests in 30.06s, 44.81MB read
Requests/sec:   1286.49
Transfer/sec:      1.49MB
```
*After:*
```bash
$ wrk -c 64 -d 30 http://localhost:4000/posts/1
Running 30s test @ http://localhost:4000/posts/1
2 threads and 64 connections
Thread Stats   Avg      Stdev     Max   +/- Stdev
Latency    43.10ms   19.98ms 191.58ms   72.16%
Req/Sec   758.54     83.87     1.00k    69.50%
45367 requests in 30.05s, 52.57MB read
Requests/sec:   1509.88 …
```
> refactor: ensure tableName is statically evaluated

- src/packages/compiler/index.js
- test/test-app/package.json
Fixes the following error.
```
Building your application...{ Error: ENOENT: no such file or directory, scandir '/Users/zacharygolba/Desktop/blog/node_modules/lux-framework/node_modules'
at Error (native)
errno: -2,
code: 'ENOENT',
syscall: 'scandir',
path: '/Users/zacharygolba/Desktop/blog/node_modules/lux-framework/node_modules' }
```
> fix: readdir error is causing cli commands to fail

- src/packages/server/request/parser/constants.js
- src/packages/server/request/parser/utils/format.js
- src/packages/server/request/test/request.test.js
When query params come in from a `GET` request, they are always a string. Often times you want them to reflect the value that they actually represent. A few of the type conversions that Lux applies to make handling query params easier were wrongfully applied to incoming JSON payloads from a `POST` or `PATCH` request. JSON can contain some of these data types that are converted, therefore we should not try to convert the string `'123'` to the number `123` as it is probably intended to be a string.
This PR ensues that these type conversions take the request method into account and do not unnecessarily/wrongfully convert certain types in incoming request bodies. Test have been added for this behavior to prevent future regressions.
Closes #499
> fix: some strings in request body cast to another type

- package.json
Switches to use the codecov [bash uploader](http://docs.codecov.io/docs/about-the-codecov-bash-uploader) rather than the npm package.
> chore: use codecov bash uploader

- src/packages/router/index.js
- src/packages/router/test/create-replacer.test.js
- src/packages/router/utils/create-replacer.js
Fixes a bug where custom routes with dynamic parts result in a 404 when using a model-less Controller.
cc @nickschot
> fix: dynamic segments are not parsed on model-less resources

- src/packages/serializer/index.js
- src/packages/serializer/test/serializer.test.js
> fix: empty 1:1 relationships are not returned in correct format

- src/packages/server/request/parser/utils/format.js
#506 made it impossible to use strings as an id in `POST` and `PATCH` requests. This PR makes it so the type cast still applies to id fields.
> fix: ids in json payloads should be cast to number

- src/packages/router/route/action/enhancers/resource.js
When returning a promise which resolves into a Query, the index route would throw an error.
See #603 for more info.
> fix: make sure result is an instanceof Query (and not just a promise) (related to #603)

- bin/lux
- src/packages/cli/commands/dbcreate.js
- src/packages/cli/commands/dbdrop.js
- src/packages/cli/errors/database-config-missing.js
Closes #624.
Also adds `-e, --environment [env]  (Default: development)` to all `db:*` commands.
> fix: properly set environment before running db:* commands

- src/packages/database/model/utils/persistence.js
- src/packages/database/test/model.test.js
@zacharygolba here's the first pass, just pushing to start the discussion on the implementation of this.
refs: #678
> feat: Add ability to specify the records id when calling model.create()

- package.json
- test/utils/debugger/rollup.config.js
- test/utils/debugger/src/debug.js
I've put together a very basic Lux development debugging utility, which significantly speeds up the process of debugging the Lux source code and test application.
To use, simply run `npm run debugger` from the root of the Lux repo. 
The debugger does the following:
1. Cleans the Lux environment => `npm run clean`
2. Builds Lux source into `/dist` => `npm run build`
3. Builds the test app => `cd test/test-app && lux build`
4. Runs node inspector => `node --inspect=4000 dist/boot.js`
5. Opens the URL in Chrome (Mac only) using an osascript (node [opn](https://github.com/sindresorhus/opn) doesn't respect `chrome-devtools` URLs)
> feat: source code & test app debugger

- src/packages/database/model/index.js
- src/packages/database/query/index.js
- src/packages/database/test/model.test.js
- src/packages/database/test/query.test.js
- test/test-app/db/seed.js
The following PR extends the coverage of Knex query methods available to Lux models.
http://knexjs.org/#Builder-whereRaw
Enables the user to build their own `where` queries. A prime example of the added flexibility this enables is building a scope for fuzzy text searching on columns:
```js
search(request) {
const whereRaw = Object.keys(request.params.search)
.reduce(([query, bindings], key, i) => {
return [
query += `${i === 0 ? '' : 'AND'} "${key}" LIKE ?`,
[...bindings, `%${request.params.search[key]}%`]
];
}, ['', []]);
const [query, bindings] = whereRaw;
return this.whereRaw(query, bindings);
}
```
http://knexjs.org/#Builder-whereBetween
http://knexjs.org/#Builder-whereNotBetween
`whereBetween` and `whereNotBetween` are implemented in the same object format as `where({})`:
```js …
```
> feat: expands Knex query coverage on models

- src/packages/pm/cluster/index.js
Fixes #702 
I've reordered the code a bit to make sure the listeners are attached before they can happen.
> fix: gracefully shutdown workers instead of waiting for the timeout to pass (fixes #702)

- bin/lux
- guide/getting-started.md
hey there, we're giving lux a shot over @carrot and one thing that took some digging to understand was the different generators the cli had. 
to help with this:
- i've added an example of passing attributes to the CLI's example
- added some details around the different `types` you can generate within the CLI. I think this list is complete, but i'm new to the codebase so i can't be sure. 
hope this feels helpful
> docs: additional documentation around cli generators

- src/packages/database/__tests__/query.test.js
- src/packages/database/query/index.js
Fixed an edge case where an empty array in a filter would result in an error.
Relevant talk in Gitter: https://github.com/postlight/lux/blob/stable/src/packages/database/query/index.js#L198-L208
> fix: filtering with an empty array as a value causes an error
