postlight/lux

README.md

chore: Link to Medium Article in Readme

---

examples/social-network/package.json
examples/todo/package.json
package.json
src/packages/cli/index.js
src/packages/cli/templates/package-json.js

Bump version to `0.0.1-beta.3` for latest release.
cc @kev5873

chore: bump version to 0.0.1-beta.3

---

package.json
src/packages/cli/commands/create.js

Just for better user experience, `npm install` is long long boring...
Signed-off-by: Albert <dev.yufan@gmail.com>

Add spinner for long-running task

---

src/packages/database/index.js

fix: globally disable orm2 cache

---

README.md

fix: correct typo in README

---

src/packages/server/utils/format-params.js
test/unit/packages/server.js

fix: strings w/ commas interpreted as an array for POST/PATCH

---

src/packages/server/index.js
src/packages/session/index.js
test/unit/packages/session.js

fix: miss-match session key/secret error

---

src/packages/serializer/index.js
test/test-app/app/serializers/authors.js
test/unit/packages/serializer.js

fix: serialize hasMany relationships

---

.travis.yml

As requested in #67 - moved this to it's own PR.

test: update travis to use npm link

---

README.md

Adds dependency status badge from [David-DM](https://david-dm.org/).

chore: add dependencies badge to README.md

---

src/packages/cli/templates/config.js

fix: config generator uses double quotes

---

src/packages/cli/templates/model-migration.js

fix: migration generator does not change - to _

---

examples/social-network/app/serializers/users.js
src/packages/serializer/index.js

fix: multiple 'hasMany' 'type' values are incorrect in serialized data

---

src/packages/fs/index.js
src/packages/fs/utils/is-js-file.js
src/packages/loader/index.js
test/unit/packages/fs.js

fix: ignore hidden and non .js files in loader

---

src/packages/controller/utils/create-page-links.js
src/packages/database/model/index.js
test/integration/controller.js
test/test-app/app/controllers/tags.js
test/test-app/app/models/tag.js
test/test-app/app/routes.js
test/test-app/app/serializers/tags.js
test/test-app/db/migrate/2016052023055747-create-tags.js

```javascript
// Page 1
links: {
self: "http://localhost:4000/tags",
first: "http://localhost:4000/tags?page=1",
last: "http://localhost:4000/tags?page=1",
prev: null,
next: null
}
// Page X
links: {
self: "http://localhost:4000/tags?page=2",
first: "http://localhost:4000/tags?page=1",
last: "http://localhost:4000/tags?page=1",
prev: "http://localhost:4000/tags?page=1",
next: null
}
```
--
Closes #102

fix: pagination links break with an empty table

---

gulpfile.babel.js
src/packages/cli/commands/db-drop.js
src/packages/cli/commands/destroy.js
src/packages/cli/commands/generate.js
src/packages/cli/utils/exec.js
src/packages/fs/index.js
src/packages/fs/utils/exists.js
src/packages/fs/utils/rmrf.js

feat: confirm overwriting files with lux generate cmd

---

.npmignore
CHANGELOG.md

chore: add CHANGELOG.md

---

README.md

As of #65 we now favor explicit `Model` import over accessing the private `store` member on a `Controller`.

docs: update readme code sample

---

src/index.js
src/packages/luxify/index.js
src/packages/luxify/utils/create-response-proxy.js

Express middleware in.
Lux middleware out.

feat: add luxify function for converting traditional middleware

---

CHANGELOG.md
examples/social-network/app/routes.js
examples/social-network/package.json
examples/todo/app/routes.js
examples/todo/bin/app.js
examples/todo/package.json

[CHANGELOG](https://github.com/postlight/lux/blob/c2140273d162df0108520586e34ee1c9aacdc3f1/CHANGELOG.md)

release: 1.0.0-rc

---

src/packages/database/model/index.js
src/packages/database/query/index.js

Adds the ability to query a model and only get one result.
```javascript
console.log(await Post.where({ isPublic: true }).first());
// => Post {}
```

feat: add Query#first and Query#last

---

CHANGELOG.md
examples/social-network/package.json
examples/todo/package.json
package.json

[CHANGELOG](https://github.com/postlight/lux/blob/9b2458a02147d7b418b2584a98cb875ffe6deb81/CHANGELOG.md#100-rc1-july-4-2016)

release: 1.0.0-rc.1

---

CHANGELOG.md

docs: update CHANGELOG.md to include docker images

---

decl/proxy.js
src/packages/luxify/utils/create-response-proxy.js

Add a complete declaration for `Proxy`.

feat: improve proxy decl

---

decl/ansi-regex.js
decl/bluebird.js
decl/chalk.js
decl/cluster.js
decl/events.js
decl/http.js
decl/inflection.js
decl/misc.js
decl/moment.js
decl/rollup.js
decl/watchman.js

Adds `// @flow` to the top of decl files.

refactor: add flow comment to the top of decl files

---

src/packages/controller/index.js
src/packages/controller/utils/find-one.js

The description of this PR is below within line comments.

fix: allow show action to be chained

---

src/packages/router/define/index.js
src/packages/router/define/interfaces.js
src/packages/router/define/utils/define-resource.js
src/packages/router/define/utils/define-route.js
src/packages/router/index.js
src/packages/router/interfaces.js

The description of this PR is below within line comments.

fix: do not allow public route definitions to set private params

---

CHANGELOG.md
examples/social-network/package.json
examples/todo/package.json
package.json

[CHANGELOG](https://github.com/postlight/lux/blob/58977d987b0ee28483879c260f934a0d3e7bc7c8/CHANGELOG.md#100-rc2-aug-2-2016)

release: 1.0.0-rc.2

---

src/packages/cli/templates/config.js

Fix: Quoting quotes inside config template

---

CHANGELOG.md
examples/social-network/package.json
examples/todo/package.json
package.json

[CHANGELOG](https://github.com/postlight/lux/blob/e59370e6d379a1e51536437ff0930071d38db531/CHANGELOG.md#100-rc3-aug-3-2016)

release: 1.0.0-rc.3

---

test/test-app/package.json

Updates test-app dependencies.

deps: update test-app dependencies

---

decl/chalk.js
decl/cluster.js
decl/events.js
decl/inflection.js
src/packages/compiler/index.js
src/packages/pm/cluster/index.js
src/packages/watcher/index.js

This PR improves the (few) third party type decls that we have.

refactor: improve third party type declarations

---

src/packages/cli/templates/model.js

fix: indentation is off when using model generators

---

CHANGELOG.md
examples/social-network/package.json
examples/todo/package.json
package.json

[CHANGELOG](https://github.com/postlight/lux/blob/68e63da4b19c6c060c54c70c8942fa511d62b9b5/CHANGELOG.md#100-rc4-aug-7-2016)

release: 1.0.0-rc.4

---

src/packages/database/index.js
src/packages/database/model/initialize-class.js
src/packages/database/utils/normalize-model-name.js
src/packages/serializer/index.js

fix: camel cased relationships do not resolve correctly

---

CHANGELOG.md
examples/social-network/package.json
examples/todo/package.json
package.json

[CHANGELOG](https://github.com/postlight/lux/blob/release-1.0.0-rc.5/CHANGELOG.md)

release: 1.0.0-rc.5

---

src/packages/application/initialize.js
src/packages/controller/index.js
src/packages/route/action/index.js
src/packages/route/params/index.js
src/packages/route/params/utils/get-data-params.js
src/packages/route/params/utils/get-query-params.js

Tests for model-less controllers will be added in #287
--
Closes #298

fix: model-less controllers prevent applications from starting

---

src/packages/database/interfaces.js
src/packages/database/utils/connect.js

This PR adds SSL and port configuration as optional properties of the database interface. It also includes them in the connect util.
--
Closes #290

Feat: Added ssl for database; fixed port

---

src/packages/cli/templates/gitignore.js

Ignoring files in `dist`, created on `lux build`.
--
Closes #325

Feat: Ignoring dist folder

---

src/packages/database/constants.js
src/packages/database/model/index.js
src/packages/database/query/utils/build-results.js

```javascript
import Post from 'app/models/posts';
let post = await Post.first();
/**
* Check existing record's persistence...
*/
post.isDirty
// => false
post.isNew
// => false
post.persisted
// => true
/**
* Check an existing record's persistence after an attribute has been changed...
*/
post.title = 'add ability to check if model has been saved';
// => 'add ability to check if model has been saved'
post.isDirty
// => true
post.isNew
// => false
post.persisted
// => false
await post.save();
/**
* Check a recently saved record's persistence...
*/
post.isDirty
// => false
post.isNew
// => false
post.persisted
// => true
post = new Post({
title: 'I have yet to be saved.'
});
/**
* Check the persistence of a record that has yet to be saved...
*/
post.isDirty
// => false
post.isNew
// => …
```

feat: add ability to check if model has been saved

---

README.md

Adds appveyor badge to README.md

chore: add appveyor badge to readme

---

CHANGELOG.md
examples/social-network/package.json
examples/todo/package.json
package.json

[CHANGELOG](https://github.com/postlight/lux/blob/3dcbbe9e55fc68c883577673d9814168f29e6fb6/CHANGELOG.md#100-rc6-sept-4-2016)

release: 1.0.0-rc.6

---

examples/social-network/app/controllers/admin/actions.js
examples/social-network/app/controllers/admin/application.js
examples/social-network/app/controllers/admin/categorizations.js
examples/social-network/app/controllers/admin/comments.js
examples/social-network/app/controllers/admin/friendships.js
examples/social-network/app/controllers/admin/notifications.js
examples/social-network/app/controllers/admin/posts.js
examples/social-network/app/controllers/admin/reactions.js
examples/social-network/app/controllers/admin/tags.js
examples/social-network/app/controllers/admin/users.js
examples/social-network/app/serializers/admin/actions.js
examples/social-network/app/serializers/admin/application.js
examples/social-network/app/serializers/admin/categorizations.js
examples/social-network/app/serializers/admin/comments.js
examples/social-network/app/serializers/admin/friendships.js
examples/social-network/app/serializers/admin/notifications.js
examples/social-network/app/serializers/admin/posts.js
examples/social-network/app/serializers/admin/reactions.js
examples/social-network/app/serializers/admin/tags.js
examples/social-network/app/serializers/admin/users.js

Updates the [social-network example](https://github.com/postlight/lux/tree/master/examples/social-network) to properly use router namespaces.

chore: update example applications

---

CHANGELOG.md
examples/social-network/package.json
examples/todo/package.json
package.json

[CHANGELOG](https://github.com/postlight/lux/blob/41434bc28b4e3e38ca58a0e2a311e7543fa3e62d/CHANGELOG.md#100-rc7-sept-4-2016)

release: 1.0.0-rc.7

---

examples/social-network/app/controllers/users.js
examples/social-network/app/models/user.js
examples/social-network/app/utils/password.js
examples/social-network/db/migrate/2016051621371582-create-users.js
examples/social-network/package.json

Follow security best practices for password storage in social network example.

chore: use bcrypt in social network example

---

src/packages/controller/index.js
src/packages/router/route/index.js
src/packages/router/route/params/test/params.test.js
src/packages/router/route/params/utils/get-default-collection-params.js
src/packages/router/route/params/utils/get-default-member-params.js
src/packages/router/route/params/utils/get-query-params.js
src/packages/router/route/test/route.test.js

This PR removes unnecessary API from the `Controller`.

refactor: cleanup unecessary controller props

---

package.json

chore(package): update eslint to version 3.7.1

---

src/packages/controller/test/find-related.test.js
src/packages/controller/test/params-to-query.test.js
src/packages/controller/utils/find-related.js

Adds unit tests for uncovered controller utils.

test: add unit tests for controller utils

---

src/packages/compiler/utils/format-name.js
src/packages/loader/builder/test/sort-by-namespace.test.js
src/packages/loader/builder/utils/create-parent-builder.js
src/packages/loader/builder/utils/sort-by-namespace.js
src/packages/loader/utils/format-key.js
src/packages/router/index.js
src/packages/router/route/constants.js
src/packages/router/route/index.js
src/packages/router/route/test/route.test.js
src/packages/router/utils/create-replacer.js
src/packages/server/request/index.js
src/packages/server/request/interfaces.js

fix: compiler does not properly format class names for nested namespaces

---

decl/sinon.js
src/packages/logger/constants.js
src/packages/logger/test/request-logger.test.js
src/packages/logger/test/writer.test.js
src/packages/logger/writer/index.js
test/utils/mocks.js

Improves test coverage for the `logger` package.

test: improve logger test coverage

---

package.json

deps: update eslint to version 3.9.1

---

CHANGELOG.md
examples/social-network/package.json
examples/todo/package.json
package.json

[CHANGELOG](https://github.com/postlight/lux/blob/8cf163035b72999f21cf3d68d4e7ffc3c85001af/CHANGELOG.md#103-nov-10-2016)

release: 1.0.3 🔧

---

src/packages/database/model/attribute/utils/create-getter.js

fix: default values override all falsy attribute values

---

CHANGELOG.md
examples/social-network/package.json
examples/todo/package.json
package.json

[CHANGELOG](https://github.com/postlight/lux/blob/8dd3f3061a018eed816095252cbd4d0fc7d1e7af/CHANGELOG.md#104-nov-12-2016)

release: 1.0.4 🔧

---

CHANGELOG.md
examples/social-network/package.json
examples/todo/package.json
package.json

[CHANGELOG](https://github.com/postlight/lux/blob/e32fb6a33f7b1029f066147b1d3559d8ccc16fe1/CHANGELOG.md#105-nov-20-2016)

release: 1.0.5 🔧

---

guide/cli.md
guide/getting-started.md
guide/route-definitions.md

Adds basic guide files (more files and updates needed).

docs: add preliminary guide files

---

CHANGELOG.md
examples/social-network/app/models/action.js
examples/social-network/app/models/comment.js
examples/social-network/app/models/post.js
examples/social-network/app/models/reaction.js
examples/social-network/app/utils/track.js
examples/social-network/db/seed.js
examples/social-network/package.json
examples/todo/db/seed.js
examples/todo/package.json
package.json

[CHANGELOG](https://github.com/postlight/lux/blob/239fc077da2bb303d94e88e24c73f253e4ebda9c/CHANGELOG.md#110-dec-10-2016)

release: 1.1.0  ✨

---

src/packages/application/index.js
src/packages/controller/index.js
src/packages/database/model/index.js
src/packages/database/model/initialize-class.js
src/packages/logger/index.js
src/packages/serializer/index.js

Adds more api docs to feed to the generator that powers [lux.postlight.com](http://lux.postlight.com).

docs: add more api docs and improve existing content

---

CHANGELOG.md
examples/social-network/package.json
examples/todo/package.json
package.json

[CHANGELOG](https://github.com/postlight/lux/blob/e1eeb8937f9858b7d76540e21dd83ad4f65300f5/CHANGELOG.md#v111-dec-28-2016)

release: v1.1.1 🔧

---

src/packages/cli/commands/dbcreate.js
src/packages/cli/commands/dbdrop.js
src/packages/cli/commands/dbseed.js
src/packages/database/utils/connect.js

fix: database is undefined when using the postgresql driver

---

CHANGELOG.md
examples/social-network/package.json
examples/todo/package.json
package.json

[CHANGELOG](https://github.com/postlight/lux/blob/f4f2e899f3673ca1889ff20200eaec35ededda02/CHANGELOG.md#v112-jan-3-2017)

release: v1.1.2 🔧

---

CHANGELOG.md
examples/social-network/package.json
examples/todo/package.json
package.json

[CHANGELOG](https://github.com/postlight/lux/blob/c15e0a7eff5cfeb68129fd10fdfb2641bacd0a27/CHANGELOG.md#v113-jan-17-2017)

release: v1.1.3 🔧

---

src/packages/cli/generator/utils/generate-type.js
src/packages/compiler/index.js
src/packages/fs/utils/exists.js
src/packages/fs/utils/rmrf.js

Fixes the following error message.
```
Error: Unexpected token (2:12)
at error (/node_modules/rollup/src/utils/error.js:2:14)
at /node_modules/rollup/src/utils/transform.js:95:6
```

fix: cli and compilation errors

---

CHANGELOG.md
examples/social-network/package.json
examples/todo/package.json
package.json

[CHANGELOG](https://github.com/postlight/lux/blob/7165b836e44ce8febe1b1e79a11e4253f94102fb/CHANGELOG.md#v114-jan-19-2017)

release: v1.1.4 🔧

---

CHANGELOG.md
examples/social-network/package.json
examples/todo/package.json
package.json
test/test-app/package.json

[CHANGELOG](https://github.com/postlight/lux/blob/58d1056bcfc84b4fa0959971bed43d608545501a/CHANGELOG.md#v115-jan-21-2017)

release: v1.1.5 🔧

---

src/packages/fs/index.js
src/packages/fs/utils/create-path-remover.js

fix: recursive readdir is broken

---

CHANGELOG.md
examples/social-network/package.json
examples/todo/package.json
package.json

[CHANGELOG](https://github.com/postlight/lux/blob/dd2e4b666fb45d2922f429500cb12f2c8dc5c891/CHANGELOG.md#v116-jan-22-2017)

release: v1.1.6 🔧

---

CHANGELOG.md
examples/social-network/package.json
examples/todo/package.json
package.json

[CHANGELOG](https://github.com/postlight/lux/blob/ccd86992f61c94b8ee4b9086f6c01068be93c188/CHANGELOG.md#v117-jan-24-2017)

release: v1.1.7 🔧

---

src/packages/controller/index.js
src/packages/router/route/index.js

docs/style: Fix typo's

---

src/packages/controller/index.js

docs: clarify afterAction docs ( fixes #687 )

---

CHANGELOG.md
examples/social-network/package.json
examples/todo/package.json
package.json

[**CHANGELOG**](https://github.com/postlight/lux/blob/55005e951ba803d5e1bf1b956da7270965b9375a/CHANGELOG.md#v120-may-16-2017)
Big thanks to @jamemackson, @nickschot, and @willviles!

release: 1.2.0 ✨

---

src/packages/responder/__tests__/__snapshots__/responder.test.js.snap
src/packages/responder/__tests__/responder.test.js
src/packages/responder/utils/data-for.js
src/utils/__tests__/env.test.js
src/utils/env.js
test/utils/set-env.js
yarn.lock

fix: detailed error messages leak into production responses

---

CHANGELOG.md
examples/social-network/package.json
examples/todo/package.json
package.json

[**CHANGELOG**](https://github.com/postlight/lux/blob/f633223fbd39ec53b620aaa58fee15b04833da91/CHANGELOG.md#v121-july-11-2017)
Big thanks to @nickschot and @kylemac!

release: v1.2.1 🔧

---

src/packages/router/route/params/index.js
src/packages/router/route/params/utils/get-data-params.js

fix: do not validate param existence for patch requests

---

CHANGELOG.md
examples/social-network/package.json
examples/todo/package.json
package.json

release: v1.2.2 🔧

---

src/packages/router/route/params/index.js
src/packages/router/route/params/utils/get-data-params.js

Fixes some eslint errors that made their way into master.

fix: eslint errors

---

src/packages/database/query/runner/utils/build-results.js
src/packages/serializer/index.js

fix: falsy IDs breaking relationships

---

CHANGELOG.md
examples/social-network/package.json
examples/todo/package.json
package.json

release: v1.2.3 🔧
